name: phone_auth_handler_demo
description: Demo for the package firebase_phone_auth_handler on pub.dev

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  maplibre_gl:
    git:
      url: https://github.com/m0nac0/flutter-maplibre-gl.git
      ref: main
  pinput: ^2.2.16
  firebase_core: ^2.1.0
  easy_container: ^1.0.4
  intl_phone_field: ^3.1.0
  firebase_phone_auth_handler:
    path: "../"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fitness_app/